name: PerWorldWarps
version: '${version}'
main: net.serveminecraft.minecrafteros.perworldwarps.PerWorldWarps
api-version: '1.13'
author: 'Adrian_oliva'
commands:
  warp:
    description: This command allows you to teleport around the world.
  warps:
    description: This command allows you to see all possible teleports in this world.
  setwarp:
    description: This command allows staff members to create new warps.
  delwarp:
    description: This command allows staff members to delete existent warps.
  perworldwarps:
    description: This command is the main command of this plugin.
    aliases:
      - pww